// Base di conoscenza: 100 domande/risposte comuni in ambito fitness, in
// italiano. Pensata per essere interrogata sia da testo che a voce (coerente
// con il resto dell'app). Le risposte sono linee guida generali evidence-based
// per un pubblico sano: non sostituiscono il parere di un medico, un
// nutrizionista o un fisioterapista, specialmente in caso di dolore,
// infortunio o condizioni di salute particolari — questo è ricordato anche
// nell'interfaccia (vedi faq.html).
const FAQ_DATA = [
    // --- 1. Allenamento generale ---
    { id: 1, category: 'Allenamento generale', question: 'Quante volte a settimana dovrei allenarmi?', answer: 'Per la maggior parte delle persone 3-4 sedute a settimana sono un buon punto di partenza, con almeno un giorno di riposo tra un gruppo muscolare e lo stesso gruppo allenato di nuovo. L\'importante è la costanza nel tempo, più che il numero esatto di sedute: meglio 3 volte a settimana per mesi che 6 volte per due settimane e poi abbandonare.' },
    { id: 2, category: 'Allenamento generale', question: 'Quanto deve durare un allenamento?', answer: 'Tra 45 e 75 minuti, riscaldamento incluso, è più che sufficiente per la maggior parte degli obiettivi. Oltre i 90 minuti la qualità dell\'esecuzione e la concentrazione tendono a calare, quindi spesso è meglio allenarsi meno ma con più intensità.' },
    { id: 3, category: 'Allenamento generale', question: 'È meglio allenarsi al mattino o alla sera?', answer: 'Non c\'è un orario "migliore" in assoluto: conta di più quando riesci ad allenarti con costanza e senza fretta. Alcuni si sentono più forti nel tardo pomeriggio/sera per il naturale aumento della temperatura corporea, altri preferiscono il mattino per abitudine e organizzazione della giornata.' },
    { id: 4, category: 'Allenamento generale', question: 'Devo sempre fare riscaldamento prima di allenarmi?', answer: 'Sì, qualche minuto di riscaldamento generale (cardio leggero) seguito da un paio di serie leggere dell\'esercizio principale riduce il rischio di infortuni e migliora la performance. Bastano 5-10 minuti, non serve renderlo un allenamento a parte.' },
    { id: 5, category: 'Allenamento generale', question: 'Posso allenarmi tutti i giorni?', answer: 'Dipende da cosa alleni e con che intensità: camminare o fare mobilità ogni giorno va benissimo, ma allenare pesantemente lo stesso muscolo senza mai un giorno di recupero aumenta il rischio di infortuni e di stallo. In genere è meglio alternare gruppi muscolari o intensità nei giorni consecutivi.' },
    { id: 6, category: 'Allenamento generale', question: 'Quanto riposo serve tra una serie e l\'altra?', answer: 'Per la forza/forza massimale 2-4 minuti, per l\'ipertrofia (crescita muscolare) 60-120 secondi, per il dimagrimento/resistenza anche 30-60 secondi. Se alla serie successiva sei ancora molto affannato o la tecnica ne risente, allunga il recupero.' },
    { id: 7, category: 'Allenamento generale', question: 'Cos\'è il sovraccarico progressivo?', answer: 'È il principio secondo cui, per continuare a migliorare, il corpo deve affrontare uno stimolo via via crescente: più peso, più ripetizioni, più serie, o più qualità di esecuzione nel tempo. Senza un progressivo aumento del carico di lavoro, dopo un po\' i progressi si fermano.' },
    { id: 8, category: 'Allenamento generale', question: 'Devo cambiare scheda ogni quanto?', answer: 'In genere ogni 6-10 settimane, o quando noti che i progressi si sono fermati nonostante l\'impegno. Non serve cambiare tutto: a volte basta variare l\'ordine degli esercizi, il numero di serie o le ripetizioni per dare nuovo stimolo.' },
    { id: 9, category: 'Allenamento generale', question: 'È normale sentire dolore muscolare il giorno dopo?', answer: 'Sì, si chiama DOMS (indolenzimento muscolare a insorgenza ritardata) ed è normale soprattutto dopo un nuovo esercizio o un carico più alto del solito. Di solito passa in 1-3 giorni; se il dolore è molto forte, localizzato in un\'articolazione o dura più di una settimana, meglio farlo controllare.' },
    { id: 10, category: 'Allenamento generale', question: 'Meglio allenamento full body o a divisione (split)?', answer: 'Entrambi funzionano: il full body (tutto il corpo ogni seduta) è spesso più efficiente per chi si allena 2-3 volte a settimana, la divisione per gruppi muscolari (split) è comoda per chi si allena 4-6 volte e vuole dedicare più volume a ogni zona. La scelta migliore è quella che riesci a seguire con costanza.' },

    // --- 2. Tecnica ed esecuzione ---
    { id: 11, category: 'Tecnica ed esecuzione', question: 'Come si esegue correttamente lo squat?', answer: 'Piedi alla larghezza delle spalle o poco più, peso ben distribuito su tutto il piede, schiena naturalmente curva (né iper-estesa né arrotondata), ginocchia che seguono la direzione delle punte dei piedi. Scendi controllando il movimento e senza far crollare il busto in avanti.' },
    { id: 12, category: 'Tecnica ed esecuzione', question: 'Perché le mie ginocchia fanno male durante lo squat?', answer: 'Spesso è una questione di tecnica (ginocchia che vanno troppo verso l\'interno, o punte dei piedi non allineate al movimento del ginocchio) o di mobilità limitata di caviglie/anche. Se il dolore persiste anche correggendo la tecnica, vale la pena farsi vedere da un fisioterapista prima di continuare a caricare peso.' },
    { id: 13, category: 'Tecnica ed esecuzione', question: 'Come evitare mal di schiena durante lo stacco?', answer: 'La cosa più importante è mantenere la schiena in posizione neutra durante tutto il movimento, senza arrotondarla, e portare il bilanciere vicino al corpo. Se non riesci a mantenere la schiena dritta con un certo peso, è il segnale che il carico è troppo alto per ora: meglio scendere di peso e lavorare sulla tecnica.' },
    { id: 14, category: 'Tecnica ed esecuzione', question: 'È normale non riuscire a fare flessioni complete?', answer: 'Assolutamente sì, è un esercizio impegnativo per chi parte da zero. Puoi partire da flessioni con le ginocchia a terra o in appoggio su un rialzo (panca, muro) e scendere gradualmente man mano che la forza aumenta.' },
    { id: 15, category: 'Tecnica ed esecuzione', question: 'Come miglioro la mobilità delle spalle?', answer: 'Esercizi di mobilità dedicati (circonduzioni, stretching della cuffia dei rotatori, mobilità toracica) fatti con regolarità, non solo una volta ogni tanto, sono la strada più efficace. Anche rinforzare i muscoli stabilizzatori della scapola aiuta molto nel tempo.' },
    { id: 16, category: 'Tecnica ed esecuzione', question: 'Meglio bilancieri o manubri?', answer: 'Non è una gara: i bilancieri permettono di caricare più peso e sono ottimi per la forza, i manubri lavorano ogni lato del corpo in modo indipendente e sono utili per correggere squilibri e per la mobilità articolare. Un buon programma spesso usa entrambi.' },
    { id: 17, category: 'Tecnica ed esecuzione', question: 'Devo sempre andare a cedimento muscolare?', answer: 'No, non è necessario ad ogni serie: andare a cedimento (non riuscire più a completare una ripetizione con tecnica corretta) ogni tanto va bene, ma farlo sempre aumenta molto la fatica e il rischio di infortunio senza dare benefici proporzionalmente maggiori.' },
    { id: 18, category: 'Tecnica ed esecuzione', question: 'Cos\'è il "range of motion" (ROM) e perché è importante?', answer: 'È l\'ampiezza del movimento con cui esegui un esercizio, dalla posizione di partenza a quella di massima estensione/flessione. Lavorare con un range di movimento completo (quando la mobilità lo permette) generalmente porta a risultati migliori rispetto a movimenti molto parziali.' },
    { id: 19, category: 'Tecnica ed esecuzione', question: 'Come capisco se sto usando il peso giusto?', answer: 'Un buon indicatore: dovresti riuscire a completare tutte le ripetizioni previste con tecnica corretta, sentendo le ultime 1-3 ripetizioni impegnative ma non impossibili. Se la tecnica peggiora molto verso la fine della serie, il peso è probabilmente troppo alto.' },
    { id: 20, category: 'Tecnica ed esecuzione', question: 'Perché è importante il core durante gli esercizi?', answer: 'Un core (addome, bassa schiena, muscoli profondi del busto) attivo stabilizza la colonna vertebrale durante quasi ogni esercizio, non solo quelli "per la pancia". Un core debole o non attivato correttamente aumenta il rischio di compensazioni e mal di schiena.' },

    // --- 3. Alimentazione e dieta ---
    { id: 21, category: 'Alimentazione', question: 'Quante proteine devo mangiare al giorno?', answer: 'Per chi si allena regolarmente, un range comune di riferimento è 1,6-2,2 grammi di proteine per kg di peso corporeo al giorno, distribuiti tra i vari pasti. Per esigenze specifiche (patologie, età, obiettivi particolari) è meglio farsi consigliare da un nutrizionista.' },
    { id: 22, category: 'Alimentazione', question: 'È vero che devo eliminare i carboidrati per dimagrire?', answer: 'No, non è necessario eliminarli: i carboidrati sono la principale fonte di energia per l\'allenamento e, se in deficit calorico (mangi meno di quanto consumi), puoi dimagrire anche mangiandone. Quello che conta di più per il dimagrimento è il bilancio calorico totale nel tempo.' },
    { id: 23, category: 'Alimentazione', question: 'Cosa mangiare prima di allenarsi?', answer: 'Un pasto con carboidrati e un po\' di proteine 1-3 ore prima aiuta ad avere energia senza sentirsi appesantiti. Se ti alleni presto la mattina, anche uno spuntino leggero 30-60 minuti prima (es. un frutto) può bastare.' },
    { id: 24, category: 'Alimentazione', question: 'Cosa mangiare dopo l\'allenamento?', answer: 'Un pasto con proteine e carboidrati entro un paio d\'ore dalla fine dell\'allenamento aiuta il recupero muscolare e il rifornimento di energia. Non serve essere ossessivi sui minuti esatti: la qualità dell\'alimentazione nell\'arco della giornata conta più del singolo pasto post-allenamento.' },
    { id: 25, category: 'Alimentazione', question: 'Quanta acqua devo bere al giorno?', answer: 'Come riferimento generale, circa 30-35 ml per kg di peso corporeo al giorno, di più nei giorni di allenamento intenso o con caldo. La sete e il colore dell\'urina (chiaro è un buon segno) sono indicatori pratici utili.' },
    { id: 26, category: 'Alimentazione', question: 'I grassi fanno male?', answer: 'No, i grassi sono un nutriente essenziale: contano piuttosto la qualità (privilegiare fonti come olio d\'oliva, frutta secca, pesce) e la quantità totale nel contesto della dieta. Eliminarli completamente non è né necessario né una buona idea per la salute.' },
    { id: 27, category: 'Alimentazione', question: 'Posso allenarmi a digiuno?', answer: 'Molte persone si allenano bene a digiuno, specialmente per allenamenti leggeri o cardio a bassa intensità; per allenamenti intensi o di forza, alcuni notano un calo di energia e performance. È soggettivo: puoi provare entrambe le opzioni e vedere cosa funziona meglio per te.' },
    { id: 28, category: 'Alimentazione', question: 'Quante calorie devo mangiare per dimagrire?', answer: 'In generale serve un moderato deficit calorico, cioè mangiare un po\' meno di quanto il corpo consuma nel complesso (attività fisica compresa). Un deficit troppo aggressivo però è difficile da sostenere ed espone al rischio di perdere anche massa muscolare: per un piano personalizzato è utile un nutrizionista.' },
    { id: 29, category: 'Alimentazione', question: 'È necessario contare le calorie?', answer: 'Non è obbligatorio, ma può essere uno strumento utile per capire quanto stai realmente mangiando, soprattutto all\'inizio. Molte persone raggiungono buoni risultati anche solo migliorando la qualità dei pasti e ascoltando la sazietà, senza contare nulla.' },
    { id: 30, category: 'Alimentazione', question: 'Meglio 3 pasti grandi o tanti piccoli pasti?', answer: 'Per la maggior parte degli obiettivi conta di più il totale di calorie e nutrienti nella giornata che la frequenza dei pasti. Scegli lo schema (3 pasti, 5 pasti, ecc.) che si adatta meglio alla tua routine e ti fa sentire bene con energia stabile.' },

    // --- 4. Integratori ---
    { id: 31, category: 'Integratori', question: 'Servono davvero gli integratori?', answer: 'Nella maggior parte dei casi no, non sono indispensabili: un\'alimentazione varia e sufficiente coprirebbe già i bisogni della maggior parte delle persone attive. Possono essere comodi per praticità (es. proteine in polvere quando manca tempo per un pasto), ma non sostituiscono una buona dieta.' },
    { id: 32, category: 'Integratori', question: 'La creatina fa male?', answer: 'La creatina monoidrato è uno degli integratori più studiati e, alle dosi comunemente usate, è considerata sicura per la maggior parte delle persone sane. Chi ha patologie renali o altre condizioni particolari dovrebbe comunque parlarne prima con un medico.' },
    { id: 33, category: 'Integratori', question: 'Cos\'è la proteina in polvere (whey)?', answer: 'È semplicemente proteine derivate dal latte (o vegetali, nelle versioni alternative) in forma di polvere, comoda per raggiungere il fabbisogno proteico giornaliero quando è difficile farlo solo con il cibo. Non è "magica": è un alimento comodo, non un farmaco.' },
    { id: 34, category: 'Integratori', question: 'Servono i BCAA?', answer: 'Se mangi già a sufficienza proteine nella giornata, i BCAA (aminoacidi ramificati) in genere non aggiungono un beneficio significativo rispetto a una dieta proteica completa. Non sono dannosi, ma spesso sono una spesa evitabile.' },
    { id: 35, category: 'Integratori', question: 'Serve la vitamina D per chi si allena?', answer: 'La vitamina D è importante per la salute delle ossa e la funzione muscolare, e molte persone (soprattutto con poca esposizione al sole) ne hanno livelli bassi. Se sospetti una carenza, il modo corretto è fare un esame del sangue e parlarne con un medico, non integrare "a caso".' },
    { id: 36, category: 'Integratori', question: 'Il caffè aiuta la performance?', answer: 'La caffeina, assunta con moderazione circa 30-60 minuti prima, è uno degli aiuti ergogenici più studiati e può migliorare percezione della fatica e performance in molte persone. Attenzione però a dosi eccessive o ad assumerla troppo tardi nella giornata, perché può disturbare il sonno.' },
    { id: 37, category: 'Integratori', question: 'Cosa sono i pre-workout?', answer: 'Sono integratori (spesso a base di caffeina e altri ingredienti stimolanti) pensati per dare energia e concentrazione prima dell\'allenamento. Non sono necessari per allenarsi bene, e vanno usati con cautela da chi è sensibile alla caffeina o si allena la sera.' },
    { id: 38, category: 'Integratori', question: 'Gli integratori bruciagrassi funzionano davvero?', answer: 'Le prove scientifiche a supporto della maggior parte di questi prodotti sono generalmente deboli o assenti: non esiste una scorciatoia che sostituisca alimentazione, allenamento e sonno per il dimagrimento. Spesso sono una spesa non necessaria.' },
    { id: 39, category: 'Integratori', question: 'Devo prendere il magnesio se ho i crampi?', answer: 'I crampi possono avere diverse cause (disidratazione, fatica muscolare, carenze minerali, altro), quindi non c\'è una risposta unica valida per tutti. Se i crampi sono frequenti o intensi, meglio parlarne con un medico piuttosto che integrare da sé senza sapere la causa.' },
    { id: 40, category: 'Integratori', question: 'Gli integratori sono sicuri per tutti?', answer: 'Non necessariamente: alcune persone (chi ha patologie, chi è in gravidanza, chi assume farmaci) devono essere più caute, e non tutti i prodotti sul mercato sono controllati con lo stesso rigore. Nel dubbio, meglio chiedere consiglio a un medico o un farmacista prima di iniziare a usarne uno nuovo.' },

    // --- 5. Dimagrimento ---
    { id: 41, category: 'Dimagrimento', question: 'Come posso dimagrire più velocemente?', answer: 'Un dimagrimento più rapido richiede un deficit calorico più aggressivo, ma questo aumenta anche il rischio di perdere massa muscolare, sentirsi stanchi e riprendere i chili in fretta dopo. Un ritmo di circa 0,5-1% del peso corporeo a settimana è generalmente più sostenibile e protegge meglio i muscoli.' },
    { id: 42, category: 'Dimagrimento', question: 'Posso dimagrire solo sulla pancia?', answer: 'No, non esiste il dimagrimento localizzato: il corpo perde grasso in modo diffuso, e da dove lo perde prima o dopo dipende soprattutto dalla genetica individuale. Allenare gli addominali tonifica il muscolo, ma non "sciogli" il grasso specificamente in quella zona facendo solo crunches.' },
    { id: 43, category: 'Dimagrimento', question: 'Il cardio a digiuno fa dimagrire di più?', answer: 'Non ci sono prove solide che il cardio a digiuno faccia perdere più grasso nel lungo periodo rispetto a farlo dopo aver mangiato: quello che conta davvero è il bilancio calorico complessivo della giornata/settimana. Fallo a digiuno solo se ti senti bene a farlo così.' },
    { id: 44, category: 'Dimagrimento', question: 'Quanto tempo serve per vedere risultati?', answer: 'Cambiamenti misurabili (peso, misure, forza) spesso si notano già dopo 3-4 settimane di costanza, mentre cambiamenti visibili all\'occhio richiedono in genere 6-12 settimane o più, a seconda del punto di partenza. La pazienza è una delle variabili più sottovalutate.' },
    { id: 45, category: 'Dimagrimento', question: 'Perché la bilancia non scende anche se mi alleno?', answer: 'Il peso sulla bilancia oscilla per molti motivi (ritenzione idrica, ciclo ormonale, digestione, aumento di massa muscolare) e non riflette solo il grasso perso. Meglio guardare la tendenza su più settimane, e affiancare altri indicatori come le misure o le foto, non solo il numero del giorno.' },
    { id: 46, category: 'Dimagrimento', question: 'Devo fare solo cardio per dimagrire?', answer: 'No: l\'allenamento di forza aiuta a mantenere (o costruire) massa muscolare durante il dimagrimento, il che rende il risultato più solido e il metabolismo più efficiente nel tempo. Una combinazione di forza, un po\' di cardio e alimentazione curata funziona meglio del solo cardio.' },
    { id: 47, category: 'Dimagrimento', question: 'Le diete drastiche funzionano?', answer: 'Nel breve termine spesso sì, ma sono difficili da sostenere a lungo e il tasso di "recupero" del peso perso dopo diete molto restrittive è alto. Un approccio più graduale e sostenibile nel tempo dà risultati che durano meglio.' },
    { id: 48, category: 'Dimagrimento', question: 'Cos\'è l\'effetto plateau nel dimagrimento?', answer: 'È il momento in cui, nonostante l\'impegno, il peso si stabilizza per un po\': è normale, spesso dovuto ad adattamenti metabolici o al fatto che il deficit calorico si è ridotto (perché pesi meno e/o ti muovi meno di prima). Di solito si supera aggiustando leggermente alimentazione o attività, non con soluzioni drastiche.' },
    { id: 49, category: 'Dimagrimento', question: 'Perdere peso velocemente è dannoso?', answer: 'Perdere peso molto rapidamente può portare a perdita di massa muscolare, stanchezza, carenze nutrizionali e più difficoltà a mantenere il risultato. Un ritmo più moderato è generalmente più sicuro e più facile da mantenere nel tempo.' },
    { id: 50, category: 'Dimagrimento', question: 'Come evito di riprendere i chili persi?', answer: 'Il modo più efficace è arrivare al peso desiderato con abitudini (alimentazione, allenamento) che intendi mantenere anche dopo, non con una dieta "temporanea" da abbandonare a obiettivo raggiunto. Mantenere l\'allenamento di forza aiuta molto a conservare il risultato nel tempo.' },

    // --- 6. Massa muscolare / forza ---
    { id: 51, category: 'Massa muscolare', question: 'Quanto tempo serve per vedere i muscoli crescere?', answer: 'I primi cambiamenti visibili si notano spesso dopo 6-8 settimane di allenamento costante con sovraccarico progressivo e alimentazione adeguata, ma la crescita muscolare significativa richiede mesi, non settimane. Anche qui la costanza conta più della velocità.' },
    { id: 52, category: 'Massa muscolare', question: 'Devo mangiare tantissimo per fare massa?', answer: 'Serve un moderato surplus calorico (mangiare un po\' più di quanto consumi), non un\'abbuffata continua: un surplus eccessivo porta soprattutto ad accumulare grasso oltre al muscolo. Un aumento graduale delle calorie, insieme a proteine adeguate, è generalmente la strada migliore.' },
    { id: 53, category: 'Massa muscolare', question: 'Le donne devono allenarsi diversamente dagli uomini per la massa?', answer: 'I principi fondamentali (sovraccarico progressivo, volume adeguato, recupero, alimentazione) sono gli stessi per tutti. Le differenze pratiche riguardano più le proporzioni ormonali e la genetica individuale che il tipo di allenamento da seguire.' },
    { id: 54, category: 'Massa muscolare', question: 'Perché non aumento di forza anche se mi alleno?', answer: 'Le cause più comuni sono: non aumentare mai il carico di lavoro nel tempo, recupero insufficiente (sonno, riposo tra le sedute), alimentazione insufficiente, o tecnica poco efficiente. Vale la pena rivedere questi punti uno per uno prima di pensare a soluzioni più complesse.' },
    { id: 55, category: 'Massa muscolare', question: 'Serve allenarsi a cedimento per crescere?', answer: 'No, non è strettamente necessario: allenarsi vicino al cedimento (con 1-3 ripetizioni "in serbo") ottiene risultati simili con meno fatica sistemica e minor rischio di infortunio rispetto ad andare sempre al limite assoluto.' },
    { id: 56, category: 'Massa muscolare', question: 'Quante serie servono per un muscolo a settimana?', answer: 'Un riferimento comune per la crescita muscolare è circa 10-20 serie efficaci per gruppo muscolare a settimana, a seconda dell\'esperienza e della capacità di recupero individuale. I principianti spesso ottengono buoni risultati anche con volumi più bassi.' },
    { id: 57, category: 'Massa muscolare', question: 'È vero che i muscoli si trasformano in grasso se smetto?', answer: 'No, muscolo e grasso sono tessuti diversi e uno non si "trasforma" nell\'altro. Se smetti di allenarti e continui a mangiare come prima, il muscolo tende a ridursi (perché non più stimolato) e può accumularsi grasso per il surplus calorico non più bilanciato dall\'attività: sono due processi paralleli, non una trasformazione.' },
    { id: 58, category: 'Massa muscolare', question: 'Gli esercizi isolati o multiarticolari sono meglio per la massa?', answer: 'Entrambi hanno un ruolo: i multiarticolari (squat, panca, trazioni) coinvolgono più muscoli e permettono carichi maggiori, gli isolati (curl, leg extension) permettono di concentrare il lavoro su un singolo muscolo. Un buon programma di solito li combina.' },
    { id: 59, category: 'Massa muscolare', question: 'Perché un braccio è più forte dell\'altro?', answer: 'È molto comune avere un lato dominante, spesso legato a quale mano usi di più nella vita quotidiana. Piccole differenze sono normali; se sono molto marcate, esercizi unilaterali (con manubri, un lato alla volta) aiutano a riequilibrare nel tempo.' },
    { id: 60, category: 'Massa muscolare', question: 'Serve il periodo di definizione dopo la massa?', answer: 'Molte persone alternano fasi di surplus calorico (per costruire muscolo) a fasi di deficit (per perdere il grasso accumulato nel frattempo), perché è difficile fare entrambe le cose insieme in modo ottimale. Non è un obbligo assoluto, ma è un approccio comune ed efficace.' },

    // --- 7. Recupero e dolori muscolari ---
    { id: 61, category: 'Recupero', question: 'Quanto devo dormire se mi alleno molto?', answer: 'Per la maggior parte degli adulti attivi, 7-9 ore di sonno di qualità sono importanti per il recupero muscolare, gli equilibri hormonali e la performance. Chi si allena intensamente e dorme poco spesso nota progressi più lenti e maggiore stanchezza.' },
    { id: 62, category: 'Recupero', question: 'Cos\'è il DOMS?', answer: 'Il DOMS (indolenzimento muscolare a insorgenza ritardata) è il dolore muscolare che compare tipicamente 24-72 ore dopo un allenamento intenso o nuovo, causato da microlesioni muscolari che il corpo poi ripara. È normale e generalmente non pericoloso, ma non è necessario cercarlo per allenarsi bene.' },
    { id: 63, category: 'Recupero', question: 'Devo allenarmi anche se ho dolori muscolari?', answer: 'Un leggero indolenzimento (DOMS) di solito non è un problema per allenarsi, anche se puoi scegliere di allenare un altro gruppo muscolare quel giorno. Se invece è un dolore acuto, localizzato in un\'articolazione o molto intenso, meglio riposare e valutare se serve un controllo medico.' },
    { id: 64, category: 'Recupero', question: 'Gli stretching prima o dopo l\'allenamento?', answer: 'Prima dell\'allenamento è meglio uno stretching dinamico (movimenti controllati) insieme al riscaldamento, mentre lo stretching statico prolungato è spesso più indicato dopo l\'allenamento o in sedute dedicate alla mobilità, perché fatto a "muscoli freddi" o prima di sforzi intensi può temporaneamente ridurre la performance.' },
    { id: 65, category: 'Recupero', question: 'Il ghiaccio o il caldo per i dolori muscolari?', answer: 'In genere il freddo è più indicato nelle prime 24-48 ore dopo un trauma acuto (gonfiore, infortunio recente), mentre il caldo è più utile per la rigidità muscolare cronica o il dolore non legato a un trauma recente. In caso di dubbio su un infortunio, meglio farsi vedere prima di trattarlo da soli.' },
    { id: 66, category: 'Recupero', question: 'Cos\'è l\'overtraining?', answer: 'È una condizione di sovrallenamento in cui il corpo non riesce più a recuperare dal carico di allenamento accumulato: si manifesta con stanchezza persistente, calo di prestazioni, disturbi del sonno o dell\'umore, e maggiore suscettibilità a infortuni. Si affronta riducendo temporaneamente il carico e dando priorità al recupero.' },
    { id: 67, category: 'Recupero', question: 'I giorni di riposo fanno perdere progressi?', answer: 'No, al contrario: il riposo è il momento in cui il corpo si adatta e si rinforza in risposta allo stimolo dell\'allenamento. Saltare sistematicamente il recupero, non i giorni di riposo, è quello che davvero frena i progressi nel tempo.' },
    { id: 68, category: 'Recupero', question: 'Il massaggio aiuta il recupero?', answer: 'Molte persone riferiscono una sensazione di minor rigidità e maggior benessere dopo un massaggio, anche se l\'effetto diretto sul recupero muscolare misurabile è probabilmente modesto. Non fa male provarlo se ti piace e ti fa sentire meglio.' },
    { id: 69, category: 'Recupero', question: 'Quando devo preoccuparmi per un dolore durante l\'allenamento?', answer: 'Un dolore acuto, improvviso, che peggiora durante il movimento, che coinvolge un\'articolazione, o accompagnato da gonfiore/instabilità va preso sul serio: meglio fermarsi e farsi valutare da un medico o un fisioterapista piuttosto che "spingere oltre" il dolore.' },
    { id: 70, category: 'Recupero', question: 'Il foam roller serve davvero?', answer: 'Molte persone lo trovano utile per la sensazione di minor rigidità muscolare e per la routine di riscaldamento/defaticamento; le prove sui benefici a lungo termine sono più deboli, ma è generalmente sicuro e piacevole da usare se ti aiuta a sentirti meglio.' },

    // --- 8. Cardio ---
    { id: 71, category: 'Cardio', question: 'Quanto cardio devo fare a settimana?', answer: 'Le linee guida generali per la salute suggeriscono almeno 150 minuti a settimana di attività aerobica moderata (o 75 minuti di attività intensa). Per obiettivi specifici di dimagrimento o performance, la quantità ideale varia da persona a persona.' },
    { id: 72, category: 'Cardio', question: 'Meglio corsa o bici per dimagrire?', answer: 'Entrambe funzionano bene per bruciare calorie: la corsa ha un impatto più alto sulle articolazioni, la bici è più delicata ma spesso richiede più tempo per lo stesso dispendio energetico. La scelta migliore è quella che riesci a fare con costanza senza dolore.' },
    { id: 73, category: 'Cardio', question: 'Cos\'è il cardio HIIT?', answer: 'HIIT (High Intensity Interval Training) alterna brevi intervalli ad altissima intensità con periodi di recupero attivo o passivo. È efficiente in termini di tempo, ma anche più impegnativo dal punto di vista del recupero, quindi non va necessariamente fatto tutti i giorni.' },
    { id: 74, category: 'Cardio', question: 'Il cardio fa perdere muscoli?', answer: 'Il cardio moderato in genere non riduce significativamente la massa muscolare, specialmente se accompagnato da un adeguato allenamento di forza e apporto proteico. Il rischio aumenta soprattutto con volumi molto alti di cardio combinati a un forte deficit calorico e poco allenamento di forza.' },
    { id: 75, category: 'Cardio', question: 'Devo fare cardio prima o dopo i pesi?', answer: 'Se l\'obiettivo principale è la forza/massa muscolare, meglio fare i pesi prima (quando sei più fresco); se l\'obiettivo principale è la performance cardio, puoi invertire l\'ordine. Se fai entrambi solo per la salute generale, l\'ordine conta relativamente poco.' },
    { id: 76, category: 'Cardio', question: 'Quanto deve durare una sessione di cardio?', answer: 'Dipende dall\'intensità: sessioni moderate spesso durano 20-45 minuti, sessioni HIIT possono essere efficaci anche in 10-20 minuti totali. Non serve necessariamente allungare oltre se l\'intensità è già alta.' },
    { id: 77, category: 'Cardio', question: 'La camminata conta come attività fisica?', answer: 'Sì, camminare a passo sostenuto è un\'attività aerobica valida e accessibile a quasi tutti, utile sia per la salute cardiovascolare che come parte di un piano di dimagrimento. Non deve essere sottovalutata solo perché "non è palestra".' },
    { id: 78, category: 'Cardio', question: 'Come si calcola la frequenza cardiaca massima?', answer: 'Una stima molto approssimativa e comune è "220 meno l\'età", anche se non è precisa per tutti individualmente. Per allenamenti mirati sull\'intensità cardiovascolare, un test più specifico (anche con un cardiofrequenzimetro nel tempo) dà indicazioni più affidabili.' },
    { id: 79, category: 'Cardio', question: 'Il cardio a bassa intensità è utile?', answer: 'Sì, il cardio a bassa intensità (camminata veloce, bici leggera) è sostenibile a lungo, utile per il recupero attivo nei giorni "leggeri" e contribuisce comunque al dispendio calorico totale della settimana. Non serve sempre "spingere al massimo" per ottenere benefici.' },
    { id: 80, category: 'Cardio', question: 'Posso fare solo pesi senza cardio?', answer: 'Sì, è possibile: l\'allenamento di forza dà comunque benefici cardiovascolari, specialmente se fatto con recuperi contenuti. Se hai obiettivi di salute cardiovascolare specifici o vuoi migliorare la resistenza, però, un po\' di cardio dedicato aiuta.' },

    // --- 9. Principianti / organizzazione ---
    { id: 81, category: 'Principianti', question: 'Da dove comincio se non ho mai fatto palestra?', answer: 'Parti con un programma semplice full body 2-3 volte a settimana, concentrandoti su pochi esercizi fondamentali (squat, spinta, trazione, core) con carichi leggeri per imparare bene la tecnica. La costanza nelle prime settimane conta più della perfezione.' },
    { id: 82, category: 'Principianti', question: 'Serve un personal trainer per iniziare?', answer: 'Non è obbligatorio, ma qualche seduta con un professionista qualificato all\'inizio può aiutarti molto a imparare la tecnica corretta e a evitare errori comuni, soprattutto sugli esercizi più tecnici come squat e stacco.' },
    { id: 83, category: 'Principianti', question: 'Quanto tempo devo dedicare in palestra ogni volta?', answer: 'Per un principiante, 45-60 minuti (riscaldamento incluso) sono generalmente più che sufficienti per una seduta efficace. Non serve restare ore per ottenere buoni risultati, soprattutto all\'inizio.' },
    { id: 84, category: 'Principianti', question: 'Ho paura di farmi male, è normale?', answer: 'Sì, è una preoccupazione molto comune per chi inizia. Partire con carichi leggeri, imparare bene la tecnica (magari con l\'aiuto di un professionista all\'inizio) e progredire gradualmente riduce di molto il rischio.' },
    { id: 85, category: 'Principianti', question: 'Meglio allenarsi in palestra o a casa?', answer: 'Entrambe le opzioni funzionano: la palestra offre più attrezzi e a volte più motivazione grazie all\'ambiente, casa offre comodità e flessibilità di orario. La scelta migliore è quella che riesci a mantenere con costanza nel tempo.' },
    { id: 86, category: 'Principianti', question: 'Quanto costa iniziare in palestra?', answer: 'Varia molto in base alla zona e al tipo di struttura, dagli abbonamenti economici alle palestre premium con più servizi. Molte palestre offrono una prova gratuita o un colloquio iniziale: è un buon modo per farsi un\'idea prima di impegnarsi.' },
    { id: 87, category: 'Principianti', question: 'Devo sapere già tutti gli esercizi prima di iniziare?', answer: 'No, assolutamente no: si imparano man mano, uno alla volta, con la pratica. Concentrati su pochi esercizi fondamentali all\'inizio piuttosto che voler imparare tutto subito.' },
    { id: 88, category: 'Principianti', question: 'Quando inizio a vedere risultati come principiante?', answer: 'I principianti spesso notano miglioramenti di forza già nelle prime 2-4 settimane (i cosiddetti "guadagni da principiante"), mentre i cambiamenti visibili nel corpo richiedono in genere un paio di mesi di costanza. È uno dei periodi in cui i progressi sono più rapidi in assoluto.' },
    { id: 89, category: 'Principianti', question: 'Serve fare test fisici prima di iniziare?', answer: 'Non è strettamente necessario per la maggior parte delle persone sane, ma se hai condizioni di salute preesistenti, sei stato a lungo sedentario, o hai dubbi particolari, un controllo medico prima di iniziare è una buona precauzione.' },
    { id: 90, category: 'Principianti', question: 'Cosa mi serve per iniziare ad allenarmi?', answer: 'Scarpe comode adatte all\'attività, abbigliamento comodo, una bottiglia d\'acqua, e non molto altro per iniziare. L\'attrezzatura specifica (fasce, cinture, ecc.) può arrivare più avanti, quando e se servirà davvero.' },

    // --- 10. Motivazione e abitudini ---
    { id: 91, category: 'Motivazione', question: 'Come rimango motivato nel tempo?', answer: 'Darsi obiettivi realistici e misurabili, festeggiare i piccoli progressi (non solo il traguardo finale), e trovare un tipo di allenamento che ti piaccia davvero aiutano molto più della sola forza di volontà. La motivazione va e viene: l\'abitudine è quello che ti fa continuare anche nei giorni "no".' },
    { id: 92, category: 'Motivazione', question: 'Cosa faccio se salto un allenamento?', answer: 'Niente di grave: riprendi semplicemente dalla seduta successiva, senza sensi di colpa e senza cercare di "recuperare" facendo il doppio. Un allenamento saltato non cancella i progressi fatti finora.' },
    { id: 93, category: 'Motivazione', question: 'Come trovo il tempo per allenarmi con una vita piena di impegni?', answer: 'Programmare l\'allenamento come un appuntamento fisso in agenda, invece di lasciarlo "se avanza tempo", aiuta molto. Anche sedute più brevi (30 minuti) fatte con costanza battono sedute lunghe fatte sporadicamente.' },
    { id: 94, category: 'Motivazione', question: 'È normale avere periodi di calo di motivazione?', answer: 'Sì, è del tutto normale ed è capitato praticamente a chiunque si alleni con costanza nel tempo. Nei periodi di calo, a volte basta ridurre l\'intensità (senza fermarsi del tutto) per non perdere l\'abitudine finché la motivazione non torna.' },
    { id: 95, category: 'Motivazione', question: 'Meglio allenarsi da solo o con un compagno?', answer: 'Dipende dalla persona: allenarsi in compagnia aiuta molti a essere più costanti e a spingersi un po\' di più, mentre altri preferiscono la concentrazione dell\'allenamento in solitaria. Prova entrambe le modalità e scegli quella che ti fa restare costante più a lungo.' },
    { id: 96, category: 'Motivazione', question: 'Come faccio a rendere l\'allenamento un\'abitudine?', answer: 'Collegarlo a un orario fisso e a un\'azione che fai già ogni giorno (es. subito dopo colazione, o appena finito di lavorare) aiuta molto a renderlo automatico. Le prime settimane sono le più difficili: dopo circa un mese diventa molto più naturale.' },
    { id: 97, category: 'Motivazione', question: 'Quanto conta la costanza rispetto all\'intensità?', answer: 'Nella maggior parte dei casi la costanza nel tempo conta di più dell\'intensità di una singola seduta: un allenamento moderato fatto per mesi batte quasi sempre un allenamento durissimo fatto sporadicamente per una settimana e poi abbandonato.' },
    { id: 98, category: 'Motivazione', question: 'Cosa faccio se non vedo risultati nonostante l\'impegno?', answer: 'Prima di tutto verifica con onestà alimentazione, sonno e reale costanza dell\'allenamento nelle ultime settimane: spesso la causa è lì. Se tutto sembra a posto e i risultati continuano a non arrivare per molte settimane, può aiutare farsi seguire da un professionista per capire cosa aggiustare.' },
    { id: 99, category: 'Motivazione', question: 'Devo fissarmi obiettivi per allenarmi meglio?', answer: 'Sì, avere un obiettivo chiaro (anche piccolo, come "fare 10 flessioni consecutive" o "correre 5 km") dà una direzione concreta e rende più facile misurare i progressi, il che a sua volta alimenta la motivazione.' },
    { id: 100, category: 'Motivazione', question: 'Come evito il confronto con gli altri in palestra?', answer: 'Ricorda che ognuno ha un punto di partenza, una genetica e una storia di allenamento diversa, quindi il confronto più utile è con te stesso di qualche settimana o mese fa, non con chi hai a fianco. Concentrarsi sui propri progressi personali rende l\'allenamento più sostenibile e meno frustrante.' }
];

// Ricerca semplice per parole in comune tra la domanda dell'utente e le
// domande/risposte della base dati (stesso approccio usato altrove nell'app
// per abbinare gli esercizi pronunciati a voce, vedi js/voice-input.js).
// Oltre a togliere gli accenti, riconduce le forme verbali più comuni della
// FAQ (mangiare, allenarsi, motivazione...) a una forma unica: senza questo,
// "allenarmi" e "allenarsi", o "mangio" e "mangiare", non si riconoscerebbero
// come la stessa parola con un confronto di sole stringhe esatte.
function faqNormalize(s) {
    let t = (s || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    t = t
        .replace(/\ballenar\w*/g, 'allenare')
        .replace(/\bmangi\w*/g, 'mangiare')
        .replace(/\b(de)?motiv\w*/g, 'motivazione')
        .replace(/\bscoraggi\w*/g, 'motivazione');
    return t;
}

const FAQ_STOPWORDS = new Set([
    'come', 'cosa', 'quando', 'perche', 'perché', 'devo', 'posso', 'sono', 'della', 'delle',
    'degli', 'dello', 'nella', 'nelle', 'per', 'con', 'una', 'uno', 'che', 'chi', 'del', 'dei',
    'dal', 'alla', 'allo', 'agli', 'alle', 'anche', 'più', 'piu', 'meglio', 'non', 'sto', 'sta',
    'stai', 'fare', 'fatto', 'molto', 'poco', 'ancora', 'oggi', 'voglio', 'vorrei', 'questo',
    'questa', 'questi', 'queste', 'quale', 'quali', 'dove', 'quanto', 'quanti', 'quanta', 'quante',
    // Parole così centrali in un'app di fitness (compaiono in 1 domanda su 5
    // o più) da non distinguere quasi nulla, anche se sembrano "specifiche"
    'allenare', 'allenamento'
]);

// Frequenza di ogni parola nel corpus (in quante domande/risposte compare):
// serve per pesare le parole rare (es. "creatina", "plank") più di quelle
// comuni ma ancora specifiche (es. "cardio", "squat"), e molto più di quelle
// generiche (es. "posso", "fare", "senza") che altrimenti basterebbero da
// sole a far scattare una risposta sbagliata solo perché compaiono ovunque.
// Scala logaritmica (idf) invece di 1/df: penalizza le parole davvero
// comuni senza schiacciare troppo quelle solo moderatamente frequenti.
const FAQ_DOC_FREQ = (function () {
    const freq = {};
    FAQ_DATA.forEach(entry => {
        const words = new Set(faqNormalize(entry.question + ' ' + entry.answer).split(/\W+/).filter(w => w.length > 2));
        words.forEach(w => { freq[w] = (freq[w] || 0) + 1; });
    });
    return freq;
})();

function faqWordWeight(word) {
    const df = FAQ_DOC_FREQ[word] || 1;
    return Math.log(FAQ_DATA.length / df + 1);
}

// Soglia minima di punteggio pesato: senza, anche parole molto comuni
// condivise per caso farebbero scattare una risposta "sicura" ma sbagliata —
// meglio non rispondere che rispondere a caso. Calibrata sui casi reali in
// test-faq.js.
const FAQ_MIN_SCORE = 5.5;

function faqSearch(query, maxResults = 3) {
    const qWords = faqNormalize(query).split(/\W+/).filter(w => w.length > 2 && !FAQ_STOPWORDS.has(w));
    if (!qWords.length) return [];
    const scored = FAQ_DATA.map(entry => {
        const qHay = faqNormalize(entry.question);
        const aHay = faqNormalize(entry.answer);
        // Le parole condivise con la domanda dell'FAQ contano doppio rispetto
        // a quelle condivise solo con la risposta (la domanda è più indicativa
        // del vero argomento), e le parole rare pesano più di quelle comuni.
        const score = qWords.reduce((acc, w) => {
            const weight = faqWordWeight(w);
            if (qHay.includes(w)) return acc + weight * 2;
            if (aHay.includes(w)) return acc + weight;
            return acc;
        }, 0);
        return { entry, score };
    }).filter(r => r.score >= FAQ_MIN_SCORE);
    scored.sort((a, b) => b.score - a.score);
    return scored.slice(0, maxResults).map(r => r.entry);
}
